CONTENT ADD: add back-end contents
Daskom-Lab/2023-Academy pull request #21
Opened 2023-12-08 07:54 UTC by vincentiusantu

I just added the back-end contents, here are the list of the material:

1. Setup
2. MySQL Intro
3. MySQL Database
4. MySQL Constraints
5. MySQL Queries
6. MySQL Operators
7. MySQL Joins
8. MySQL References
9. PHP Intro
10. PHP DB Connection
11. PHP Show Data
12. PHP Store Data
13. PHP Update Data
14. PHP Delete Data
15. Back-End References

2023-12-08 09:12 UTC, IritaSee commented on resources/back_end/003_mysql_database.md
in the part, since we are using markdown, i think it is better to use backtick to refer to a variable name or something in the code, I suggest, instead of this:

For example, you want to create database named students. You can use this command:

do this


For example, you want to create database named `students`. You can use this command:

2023-12-08 09:12 UTC, IritaSee commented on resources/back_end/003_mysql_database.md
This is to avoid confusion between a part of the code, or talking about something else

2023-12-08 09:23 UTC, IritaSee requested changes
It is ultra challenging to create a very compact material in backend programming, goodjob! @vincentiusantu 

Just a little image to help them understand the SQL `JOIN` and code variable formatting will do

2023-12-08 09:23 UTC, IritaSee commented on resources/back_end/007_mysql_joins.md
I'd advice to add some image, and/or hyperlink to make it easier in undertanding joins, 
Like this perhaps
https://www.codeproject.com/KB/database/Visual_SQL_Joins/Visual_SQL_JOINS_orig.jpg

2023-12-08 12:00 UTC, fakhrip commented on resources/back_end/003_mysql_database.md
> in the part, since we are using markdown, i think it is better to use backtick to refer to a variable name or something in the code, I suggest, instead of this:
> 
> For example, you want to create database named students. You can use this command:
> 
> do this
> 
> 
> For example, you want to create database named `students`. You can use this command:
> 

I think there is something wrong happened when you edited this one(?) since this comment looks confusing by itself ga wkwk

2023-12-08 12:05 UTC, fakhrip commented
Agreed, this is a very good job for initializing the backend tutorial content!

Just keep in mind to always make these contents better every single year so everyone could learn easier and better too 👍

2023-12-09 03:32 UTC, vincentiusantu commented
Thanks for the review sir(s) :D I'm merging it now as I've done the revision

2023-12-09 03:33 UTC, merged

2023-12-09 03:39 UTC, IritaSee commented on resources/back_end/003_mysql_database.md
🤣 I struggled to explain what's inside of my head. Apologies 🥲

My point was, please differentiate the instructions and in code 'variables' using backtick

2023-12-09 03:52 UTC, fakhrip commented on resources/back_end/003_mysql_database.md
i see, sure no problem, and yes i agree with this, please note this one down for future changes @vincentiusantu using backtick to show variable and/or technical terms is a good practice to avoid reader confusion